/* DO NOT EDIT THIS FILE - it is machine generated */
#include "it_geomind_myfirstapp_DisplayMessageActivity.h"

/*
 * Class:     it_geomind_myfirstapp_DisplayMessageActivity
 * Method:    callNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_geomind_myfirstapp_DisplayMessageActivity_callNative
  (JNIEnv * env, jobject obj)
  {
    return (*env) -> NewStringUTF( env, "NDK Sample Test !" );
  }
