/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abacogroup_dbmap_wms_tile_NavionicsDriver */

#ifndef _Included_com_abacogroup_dbmap_wms_tile_NavionicsDriver
#define _Included_com_abacogroup_dbmap_wms_tile_NavionicsDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_abacogroup_dbmap_wms_tile_NavionicsDriver
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_abacogroup_dbmap_wms_tile_NavionicsDriver_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_abacogroup_dbmap_wms_tile_NavionicsDriver
 * Method:    getTile
 * Signature: (IFFFF[B)I
 */
JNIEXPORT jint JNICALL Java_com_abacogroup_dbmap_wms_tile_NavionicsDriver_getTile
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
