/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_geomind_myfirstapp_GeoFlyerViewController */

#ifndef _Included_it_geomind_myfirstapp_GeoFlyerViewController
#define _Included_it_geomind_myfirstapp_GeoFlyerViewController
#ifdef __cplusplus
extern "C" {
#endif
#undef it_geomind_myfirstapp_GeoFlyerViewController_MODE_PRIVATE
#define it_geomind_myfirstapp_GeoFlyerViewController_MODE_PRIVATE 0L
#undef it_geomind_myfirstapp_GeoFlyerViewController_MODE_WORLD_READABLE
#define it_geomind_myfirstapp_GeoFlyerViewController_MODE_WORLD_READABLE 1L
#undef it_geomind_myfirstapp_GeoFlyerViewController_MODE_WORLD_WRITEABLE
#define it_geomind_myfirstapp_GeoFlyerViewController_MODE_WORLD_WRITEABLE 2L
#undef it_geomind_myfirstapp_GeoFlyerViewController_MODE_APPEND
#define it_geomind_myfirstapp_GeoFlyerViewController_MODE_APPEND 32768L
#undef it_geomind_myfirstapp_GeoFlyerViewController_MODE_MULTI_PROCESS
#define it_geomind_myfirstapp_GeoFlyerViewController_MODE_MULTI_PROCESS 4L
#undef it_geomind_myfirstapp_GeoFlyerViewController_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define it_geomind_myfirstapp_GeoFlyerViewController_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef it_geomind_myfirstapp_GeoFlyerViewController_BIND_AUTO_CREATE
#define it_geomind_myfirstapp_GeoFlyerViewController_BIND_AUTO_CREATE 1L
#undef it_geomind_myfirstapp_GeoFlyerViewController_BIND_DEBUG_UNBIND
#define it_geomind_myfirstapp_GeoFlyerViewController_BIND_DEBUG_UNBIND 2L
#undef it_geomind_myfirstapp_GeoFlyerViewController_BIND_NOT_FOREGROUND
#define it_geomind_myfirstapp_GeoFlyerViewController_BIND_NOT_FOREGROUND 4L
#undef it_geomind_myfirstapp_GeoFlyerViewController_BIND_ABOVE_CLIENT
#define it_geomind_myfirstapp_GeoFlyerViewController_BIND_ABOVE_CLIENT 8L
#undef it_geomind_myfirstapp_GeoFlyerViewController_BIND_ALLOW_OOM_MANAGEMENT
#define it_geomind_myfirstapp_GeoFlyerViewController_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef it_geomind_myfirstapp_GeoFlyerViewController_BIND_WAIVE_PRIORITY
#define it_geomind_myfirstapp_GeoFlyerViewController_BIND_WAIVE_PRIORITY 32L
#undef it_geomind_myfirstapp_GeoFlyerViewController_BIND_IMPORTANT
#define it_geomind_myfirstapp_GeoFlyerViewController_BIND_IMPORTANT 64L
#undef it_geomind_myfirstapp_GeoFlyerViewController_BIND_ADJUST_WITH_ACTIVITY
#define it_geomind_myfirstapp_GeoFlyerViewController_BIND_ADJUST_WITH_ACTIVITY 128L
#undef it_geomind_myfirstapp_GeoFlyerViewController_CONTEXT_INCLUDE_CODE
#define it_geomind_myfirstapp_GeoFlyerViewController_CONTEXT_INCLUDE_CODE 1L
#undef it_geomind_myfirstapp_GeoFlyerViewController_CONTEXT_IGNORE_SECURITY
#define it_geomind_myfirstapp_GeoFlyerViewController_CONTEXT_IGNORE_SECURITY 2L
#undef it_geomind_myfirstapp_GeoFlyerViewController_CONTEXT_RESTRICTED
#define it_geomind_myfirstapp_GeoFlyerViewController_CONTEXT_RESTRICTED 4L
#undef it_geomind_myfirstapp_GeoFlyerViewController_RESULT_CANCELED
#define it_geomind_myfirstapp_GeoFlyerViewController_RESULT_CANCELED 0L
#undef it_geomind_myfirstapp_GeoFlyerViewController_RESULT_OK
#define it_geomind_myfirstapp_GeoFlyerViewController_RESULT_OK -1L
#undef it_geomind_myfirstapp_GeoFlyerViewController_RESULT_FIRST_USER
#define it_geomind_myfirstapp_GeoFlyerViewController_RESULT_FIRST_USER 1L
#undef it_geomind_myfirstapp_GeoFlyerViewController_DEFAULT_KEYS_DISABLE
#define it_geomind_myfirstapp_GeoFlyerViewController_DEFAULT_KEYS_DISABLE 0L
#undef it_geomind_myfirstapp_GeoFlyerViewController_DEFAULT_KEYS_DIALER
#define it_geomind_myfirstapp_GeoFlyerViewController_DEFAULT_KEYS_DIALER 1L
#undef it_geomind_myfirstapp_GeoFlyerViewController_DEFAULT_KEYS_SHORTCUT
#define it_geomind_myfirstapp_GeoFlyerViewController_DEFAULT_KEYS_SHORTCUT 2L
#undef it_geomind_myfirstapp_GeoFlyerViewController_DEFAULT_KEYS_SEARCH_LOCAL
#define it_geomind_myfirstapp_GeoFlyerViewController_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef it_geomind_myfirstapp_GeoFlyerViewController_DEFAULT_KEYS_SEARCH_GLOBAL
#define it_geomind_myfirstapp_GeoFlyerViewController_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef it_geomind_myfirstapp_GeoFlyerViewController_HONEYCOMB
#define it_geomind_myfirstapp_GeoFlyerViewController_HONEYCOMB 11L
#undef it_geomind_myfirstapp_GeoFlyerViewController_MSG_REALLY_STOPPED
#define it_geomind_myfirstapp_GeoFlyerViewController_MSG_REALLY_STOPPED 1L
#undef it_geomind_myfirstapp_GeoFlyerViewController_MSG_RESUME_PENDING
#define it_geomind_myfirstapp_GeoFlyerViewController_MSG_RESUME_PENDING 2L
/*
 * Class:     it_geomind_myfirstapp_GeoFlyerViewController
 * Method:    CreateGeoFlyerController
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_it_geomind_myfirstapp_GeoFlyerViewController_CreateGeoFlyerController
  (JNIEnv *, jobject);

/*
 * Class:     it_geomind_myfirstapp_GeoFlyerViewController
 * Method:    DestroyGeoFlyerController
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_it_geomind_myfirstapp_GeoFlyerViewController_DestroyGeoFlyerController
  (JNIEnv *, jobject, jlong);

/*
 * Class:     it_geomind_myfirstapp_GeoFlyerViewController
 * Method:    GeoFlyerControllerShowDialog
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_it_geomind_myfirstapp_GeoFlyerViewController_GeoFlyerControllerShowDialog
  (JNIEnv *, jobject, jlong);

/*
 * Class:     it_geomind_myfirstapp_GeoFlyerViewController
 * Method:    OnMessageBoxResult
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_it_geomind_myfirstapp_GeoFlyerViewController_OnMessageBoxResult
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
